services:
  - type: web
    name: envanterqr-app
    runtime: python3
    plan: starter
    buildCommand: bash build_alt.sh
    startCommand: python3 render_startup_alt.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        scope: build
        value: 3.11.6
      - key: DATABASE_URL
        scope: secret
      - key: SESSION_SECRET
        scope: secret
      - key: B2_APPLICATION_KEY_ID
        scope: secret
      - key: B2_APPLICATION_KEY
        scope: secret
      - key: B2_BUCKET_NAME
        value: envanter-qr-bucket
      - key: ADMIN_COUNT_PASSWORD
        scope: secret
    autoDeploy: false

# NOTE: All secret environment variables must be set in Render Dashboard
# Do NOT commit actual credential values to this file